export const FETCH_QUAKE_DATA = 'FAKE_QUAKE_DATA';
export const FETCH_CURRENT_LOCATION = 'FETCH_CURRENT_LOCATION';
export const DIALOG_STATUS = 'DIALOG_STATUS';
export const SET_MAP_REGION = 'SET_MAP_REGION';
export const TEST_ACTION = 'TEST_ACTION';